import { wrapper } from '@/app/store/store'
import {
  getComedy,
  getFamily,
  getFantasy,
  getGenres,
  getNowPlaying,
  getPopular,
  getRunningQueriesThunk,
  getTopRating,
  getUpComing,
  useGetComedyQuery,
  useGetFamilyQuery,
  useGetFantasyQuery,
  useGetNowPlayingQuery,
  useGetPopularQuery,
  useGetUpComingQuery,
} from '@/features/movies/api/movie-api'
import { Genres } from '@/features/movies/ui/Genres/Genres'
import { MovieList } from '@/features/movies/ui/MovieList/MovieList'
import { NewMovie } from '@/features/movies/ui/NewMovie/NewMovie'
import { Page } from '@/shared/types/layout'
import { Preloader } from '@/shared/ui/Preloader/Preloader'
import Layout from '@/widgets/layout/ui/layout'
import { Meta } from '@/widgets/meta/Meta'

export const getServerSideProps = wrapper.getServerSideProps(store => async context => {
  store.dispatch(getPopular.initiate())
  store.dispatch(getGenres.initiate())
  store.dispatch(getTopRating.initiate())
  store.dispatch(getNowPlaying.initiate())
  store.dispatch(getUpComing.initiate())
  store.dispatch(getComedy.initiate())
  store.dispatch(getFamily.initiate())
  store.dispatch(getFantasy.initiate())

  await Promise.all(store.dispatch(getRunningQueriesThunk()))

  return {
    props: {},
  }
})

const Home: Page = () => {
  const { data: fantasy } = useGetFantasyQuery()
  const { data: nowPlaying } = useGetNowPlayingQuery()
  const { data: upComing } = useGetUpComingQuery()
  const { data: comedy } = useGetComedyQuery()
  const { data: family, isLoading: isListLoad } = useGetFamilyQuery()
  const { data: popular, isLoading: isPopularLoad } = useGetPopularQuery()

  return (
    <>
      <Meta content={'Generated by create next app'} name={'description'} />
      {isPopularLoad ? <Preloader /> : <NewMovie data={popular} />}
      <Genres />
      {isListLoad ? (
        <Preloader />
      ) : (
        <>
          <MovieList data={comedy} title={'Комедийные фильмы'} />
          <MovieList data={nowPlaying} title={'Новые фильмы'} />
          <MovieList data={family} title={'Смотрим всей семьей'} />
          <MovieList data={upComing} title={'Скоро выйдут'} />
          <MovieList data={fantasy} title={'Фантастика'} />
        </>
      )}
      <div style={{ lineHeight: 1.4, margin: '0 auto', maxWidth: '1400px', padding: '20px 0' }}>
        <h2 style={{ marginBottom: 15 }}>
          Добро пожаловать на Kinomore - онлайн кинотеатр с более чем 960 тысячами фильмов!
        </h2>
        <p style={{ fontSize: 18 }}>
          У нас вы можете легко и быстро найти интересующий вас фильм благодаря нашему удобному
          <br />
          поиску. Мы предлагаем широкий выбор кинокартин различных жанров и направлений - от
          классики
          <br />
          до новинок, от драм до боевиков. На Kinomore вы сможете насладиться просмотром любимых
          <br />
          фильмов в высоком качестве в любое время и в любом месте. Регистрируйтесь на нашем сайте и
          <br />
          начните погружаться в увлекательный мир кино!
          <br />
        </p>
      </div>
    </>
  )
}

Home.getLayout = page => <Layout>{page}</Layout>

export default Home
